<?php

namespace Bloum;

require_once dirname(__FILE__) . '/../../core/Url.php';

/**
 * Test class for Url.
 * Generated by PHPUnit on 2012-05-14 at 17:37:56.
 */
class UrlTest extends \PHPUnit_Framework_TestCase {

    /**
     * @dataProvider data
     * @test
     */
    public function testExplode($url, $controller, $action) {

        /** TESTE 1 * */
        $urlManager = new Url($url);
        $this->assertEquals($controller, $urlManager->getController());
        $this->assertEquals($action, $urlManager->getAction());

        
    }

    public function data() {
        return array(
            array("user", "user", "index"),
            array("user.save", "user", "save"),
            array("user.", "user", "index"),
            array("", "index", "index"),
            array(null)
        );
    }

}

?>
